### ISSUE TITLE
Perhaps some clarification on creating roles

### ISSUE THREAD

**Issue by gavinggordon** [httpoz/roles#10]
Most of your examples are pretty well explained. However, regarding the small section on creating roles, I'm finding it hard to understand where such methods would be used. I'm not a complete beginner with Laravel, but I'm also no expert. 

My assumption is that you would put the aforementioned methods in an database seeder, though, I'm unsure; if you provide an example of where one would use such methods, that may help me, and possibly others, understand. 

Keep up the awesome work!

**Comment by httpoz** [comment]
Ideally you would use such methods in the seeder yes, but sometimes you can use these post project setup to create and assign roles via a user interface in your application. I will add clarity to the documentation.

**Comment by gavinggordon** [comment]
Thank you. 😊
