### ISSUE TITLE
Attaching, Syncing And Detaching Roles should explain briefly 

### ISSUE THREAD

**Issue by kantsverma** [httpoz/roles#11]
I am using your code for user role its working fine now But stuck on point 'Attaching, Syncing And Detaching Roles' you should make it more easy and clear to understand. That will be helpful for all.

I also want to create a group in rout how can i check the group in route file ?

**Comment by httpoz** [comment]
To check for a group in routes you would leverage middleware like this:

```php
Route::get('/example', [
    'as' => 'example',
    'middleware' => 'group:application.managers',
    'uses' => 'ExampleController@index',
]);
```

I will work on improving the documentation.
