### ISSUE TITLE
Catching the exceptions inside Handler

### ISSUE THREAD

**Issue by AdoZiad** [httpoz/roles#12]
Hello,

I have followed the instructions to implement this package into Laravel 5.3 fresh installation and i'm not able to catch the exception on `RoleDeniedException`, i just get an empty page.

Any idea why it's not throwing the exception? I'm new to Laravel...

Thanks in advance for your help.

Kind regards.

**Comment by httpoz** [comment]
Hi,

Sorry for the late response. I cannot replicate the issue. Can you confirm the `sources/views/vendor/roles/error.blade.php` view exists?
