### ISSUE TITLE
Redirecting user to specific page

### ISSUE THREAD

**Issue by pwnz22** [httpoz/roles#13]
I'm using Laravel 5.3 and Auth by default. How can i do the normal user redirection if i have similar roles and also pages for them. For example i have **AdminRole** and after the **Login** i want to redirect user to `/admin/dashboard`. 

I tried something like this but it doesn't make sense:
```
protected function redirectTo()
{
    if (Auth::user()->isRole('admin'))
        return redirect()->route('admin');

    return redirect()->route('home');
}
```

**Comment by httpoz** [comment]
I actually do the same thing, I always have a HomeController or DashboardController with a single index method that has an if statement like the one you have above to serve different views depending on the role. So I do this because this is usually my app's single entry point. Every other content I serve is managed by showing the contextual links to the right user as per their role.

**Comment by JPortegijs** [comment]
I have the same thing, but once in my dashboard I have to login everytime I click on a link within the dashboard. Anything I can do to fix this?

**Comment by httpoz** [comment]
could you share your routes file. and the controller you use to route traffic after login.

**Comment by JPortegijs** [comment]
LoginController:

    protected function redirectTo()
    {
        $user = Auth::user();

        if($user->hasRole('admin'))
        {
            return '/admin/dashboard';
        } else {
            return '/';
        }
    }

routes/web.php:

Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/contact', 'ContactController@index');

Route::get('/admin/dashboard', [
    'as' => 'admin',
    'middleware' => 'role:admin',
    'uses' => 'Admin\AdminController@index',
]);

Route::get('/admin/cars', [
    'as' => 'cars',
    'middleware' => 'role:admin',
    'uses' => 'Admin\CarsController@index',
]);

Route::get('/admin/reservations', [
    'as' => 'reservations',
    'middleware' => 'role:admin',
    'uses' => 'Admin\ReservationsController@index',
]);

Thanks for the quick reply!

**Comment by JPortegijs** [comment]
I`m sorry, I seem to have it fixed. I was doing href="{{ Auth::logout() }}" instead of creating a route to /logout. This deleted my session on every request.

**Comment by httpoz** [comment]
Glad you found a fix :-)
