### ISSUE TITLE
Usage of role middleware

### ISSUE THREAD

**Issue by blogui91** [httpoz/roles#14]
Hello,
I am having a weird issue using 'role:admin' middleware.

 I am using Laravel 5.3 and I have a file in routes/admin.php which contains routes which must be accessed only by the admin. 
Then i added the function mapAdminRoutes() in app\Providers\RouteServiceProvider.php

```
  protected function mapAdminRoutes()
    {
        Route::group([
            'middleware' => ['role:admin'],
            'namespace' => $this->admin_namespace,
            'prefix' => 'admin',
        ], function ($router) {
            require base_path('routes/admin.php');
        });
    }

```

In this same file (RouteServiceProvider.php) i left the function ``` map() ``` like this:
```
/**
     * Define the routes for the application.
     *
     * @return void
     */
    public function map()
    {
        $this->mapApiRoutes();
        $this->mapWebRoutes();
        $this->mapAdminRoutes();
    }
```

Then, when I login and i try to access in any admin route, i  says i dont have permission to access there. 
```
RoleDeniedException in VerifyRole.php line 43:
You don't have a required ['admin'] role.
```

Checking the file ``HttpOz\roles\Middleware\VerifyRole.php``` i noticed that $this->auth->check() is returning false, my suspect was, the current user was not being saved in session, so i added 'web' middleware.  

```
protected function mapAdminRoutes()
    {
        Route::group([
            'middleware' => ['web','role:admin'],
            'namespace' => $this->admin_namespace,
            'prefix' => 'admin',
        ], function ($router) {
            require base_path('routes/admin.php');
        });
    }
```

Finally it worked, however the session expires so fast and when i logged out appears MismatchTokenException (I think because session has ended) :( 
Can you help me? Thanks in advance.

**Comment by httpoz** [comment]
Are you trying to implement this on a fresh install? That does sound like a session issue, I will however try to replicate the issue. Do try the usual ```php artisan clear-compiled```

**Comment by blogui91** [comment]
Hi @httpoz Yes, you are right, The reason is $this->auth->user() only works with 'web' middleware  so, i moved some items from $web array located in ``` app\Http\Kernel.php ``` to the variable $middleware. Like this
```
<?php

namespace App\Http;

use Illuminate\Foundation\Http\Kernel as HttpKernel;

class Kernel extends HttpKernel
{
    /**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array
     */
    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \App\Http\Middleware\Cors::class,
            \Illuminate\Session\Middleware\StartSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            
    ];

    /**
     * The application's route middleware groups.
     *
     * @var array
     */
    protected $middlewareGroups = [
        'web' => [
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
            \Laravel\Passport\Http\Middleware\CreateFreshApiToken::class,
        ],

        'api' => [
            'throttle:60,1',
            'bindings',
        ]

    ];

    /**
     * The application's route middleware.
     *
     * These middleware may be assigned to groups or used individually.
     *
     * @var array
     */
    protected $routeMiddleware = [
        'auth' => \Illuminate\Auth\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'bindings' => \Illuminate\Routing\Middleware\SubstituteBindings::class,
        'can' => \Illuminate\Auth\Middleware\Authorize::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
        'role' => \HttpOz\Roles\Middleware\VerifyRole::class,
        'group' => \HttpOz\Roles\Middleware\VerifyGroup::class,
    ];
}

```

It looks good but it's the same case, it works but session closes, I checked storage\framework\sessions and i noticed it's creating a new file on refresh page :/ 

***reference*** https://laracasts.com/discuss/channels/laravel/authuser-return-null-on-laravel-52

**Comment by blogui91** [comment]
I think, the problem is my browser, I have tested this issue with Edge and it seems to work perfectly, With Chrome is not :/ i will check other threads, Thank you!

**Comment by httpoz** [comment]
Sorry I couldn't help, do let me know if you find the root of the problem.
