### ISSUE TITLE
Call to a member function attachRole() on integer error

### ISSUE THREAD

**Issue by Albure** [httpoz/roles#15]
I'm getting this error when trying to assign a role and am not sure what to do about it.

Do I need to define attachRole() in my config? That isn't mentioned anywhere so I assumed not

https://gyazo.com/b5388fb9b72ddc97e73ea0eed2f48aee

EDIT: I have a feeling like I am not using this method correctly at all. I've passed my roles to my database but am not sure how to assign the roles correctly

**Comment by httpoz** [comment]
I'll need you to try a few things:

Firstly I'll assume your **client** role has the slug **client**, so before your if statement:

```php
$clientRole = Role::whereSlug('client')->first();
```

the same would go for your employee role:

```php
$employeeRole = Role::whereSlug('employee')->first();
```

**Comment by Albure** [comment]
Still receiving this error https://gyazo.com/632f785d30772b12178fa38aa1b310c8

You defined the variables, which is great as that would have thrown as error as well but this error is in the way still

current code: https://gyazo.com/64ad101465235827b28872cc2201387e

**Comment by httpoz** [comment]
Could you show me your User model?

**Comment by Albure** [comment]
https://gyazo.com/f67ca3375312d5a8b559273430b5726a

Thanks for helping me through this

**Comment by httpoz** [comment]
Also use `Auth::user()` as opposed to `Auth::id()`. That should be it.

**Comment by Albure** [comment]
Perfect!

If you wouldn't mind helping me understand, why user `Auth::user()` instead of `Auth::id()` ?

In addition `$clientRole = Role::whereSlug('client')->first();` wasn't included in the documentation. Did I present a scenario that needed a unique addition? Or should I use this logic whenever I assign a role?

**Comment by httpoz** [comment]
`Auth::user` will return the whole User object (instance of the Eloquent model) while `Auth::id()` returns just the ID of the authenticated user, this is a wild guess I would have to verify when I get to a computer and give you a better explanation.

The documentation is lacking as cited by many of the open issues and I'm beginning an effort to clean up and have more code examples in the documentation but yes everytime you assign a role, you need to first find the role and then assign it to a user object.

I'll keep this issue open if you don't mind and tag it for documentation so I don't forget to clarify this in documentation.

**Comment by Albure** [comment]
That makes sense and I think I know how I can work with it.

Sounds good. What you're offering is at the very least pretty helpful to me so thanks!
