### ISSUE TITLE
Route "Key" Parameters?

### ISSUE THREAD

**Issue by Albure** [httpoz/roles#17]
Is there a resource I can use, or an explanation, to understand the `as` ?
Code:
`$router->get('/example', [
    'as' => 'example',
    'middleware' => 'role:admin',
    'uses' => 'ExampleController@index',
]);`

**Comment by httpoz** [comment]
While this works it's also a 5.2 implementation, I will again update the docs for more relevance.

[Named Routes in Laravel Documentation](https://laravel.com/docs/5.2/routing#named-routes)

**Comment by Albure** [comment]
Sorry to kinda push that point. While good documentation is of course valuable the reason I asked was simply to gain more understanding. Not trying to bag on you at all. You've been a great help

**Comment by httpoz** [comment]
Did you manage to understand from the laravel documentation? I could explain it the way I understand it if not.
