### ISSUE TITLE
Update to Laravel 5.4

### ISSUE THREAD

**Issue by PauMin** [httpoz/roles#19]
Laravel 5.4 came out, please update the dependencies.

Problem 1
    - Conclusion: remove laravel/framework v5.4.4
    - Conclusion: don't install laravel/framework v5.4.4
    - httpoz/roles v1.4.0 requires illuminate/support 5.3.* -> satisfiable by illuminate/support[v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - httpoz/roles v1.4.1 requires illuminate/support 5.3.* -> satisfiable by illuminate/support[v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - don't install illuminate/support v5.3.0|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.3.16|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.3.23|don't install laravel/framework v5.4.4
    - don't install illuminate/support v5.3.4|don't install laravel/framework v5.4.4
    - Installation request for laravel/framework (locked at v5.4.4, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.4].
    - Installation request for httpoz/roles ^1.4 -> satisfiable by httpoz/roles[v1.4.0, v1.4.1].

**Comment by httpoz** [comment]
Give me a few hours to get to a computer. Thanks.

**Comment by httpoz** [comment]
#20 

Let me know if you encounter any issues. Thanks.
