### ISSUE TITLE
Class 'HttpOz\Roles\RolesServiceProvider' not found 

### ISSUE THREAD

**Issue by nikolaynesov** [httpoz/roles#2]
There is an issue that does not happen with original package.
It happens after package installation.

> [Symfony\Component\Debug\Exception\FatalThrowableError]  
>   Class 'HttpOz\Roles\RolesServiceProvider' not found

**Comment by nikolaynesov** [comment]
[pull/3](https://github.com/httpoz/roles/pull/3)

**Comment by httpoz** [comment]
I did notice that and I have to run `composer dump-autoload -o` once or twice before it actually registers. Looking into it now.

**Comment by httpoz** [comment]
#3
