### ISSUE TITLE
Enormous struggle..

### ISSUE THREAD

**Issue by JPortegijs** [httpoz/roles#23]
Hey, I`ve been trying to use your package and can't seem to get it to work.

I have two users in my database: 
user_id 1 = admin.
user_id 2 = user.

If I run:

use HttpOz\Roles\Models\Role;

protected function redirectTo()
{
        $isAdmin = Role::find(1)->users;

        if ($isAdmin) {
            dd('Is admin');
        } else {
            dd('Is not admin');
        }
}

Then both of the users return true: 'Is admin', while user_id 2 should not be admin.

Anything I`m doing wrong?

**Comment by httpoz** [comment]
Apologies for the late response. Well from what I see, you are querying the Roles model to find if it has users, so your condition block will always return true for 1 or 2 assuming your role IDs are 1 and 2 respectively because each role has atleast one person.

What I suggest is the following:

```php
// I am assuming you are checking as the user logged in? If so, let's get the authenticated user
$user = Auth::user();

// then let's validate if said user is of the required role. I'm assuming the slug for your admin role is 'admin'
if($user->isRole('admin')){
    dd('Is Admin');
} else {
    dd('Is not admin');
}
```

**Comment by JPortegijs** [comment]
That works like a charm! Thank you so much!
