### ISSUE TITLE
Caching Roles?

### ISSUE THREAD

**Issue by cjmaxik** [httpoz/roles#26]
Hello. This is a suggestion about roles caching. It might be handsome.

**Comment by httpoz** [comment]
I'm happy to look into it, could you perhaps give me a use case as well?

**Comment by cjmaxik** [comment]
So, you don't need to catch user roles from DB every time. 
I personally have a project that heavily depends on roles and groups. You can see some implementations here: https://github.com/kodeine/laravel-acl/blob/1.0/src/Kodeine/Acl/Traits/HasRole.php#L39

**Comment by httpoz** [comment]
I'll start working on this

**Comment by httpoz** [comment]
Hi @cjmaxik I have added caching. Please confirm if you are happy with this, use master branch.

**Comment by cjmaxik** [comment]
@httpoz https://github.com/httpoz/roles/pull/31 and we're good to go, I think.

**Comment by cjmaxik** [comment]
@httpoz Please revert the changes. There is some weird bug which cause role attribute to be empty. I will provide more information later.

**Comment by httpoz** [comment]
done. Noticed the blank too if you try to retrieve cached roles. reverted and verified.

**Comment by cjmaxik** [comment]
So, I want to point it again - in current implementation trait cached only first user role occurrence. It is definitely not good.

```php
>>> Cache::flush()
=> true
>>> App\Models\User::find(1)->getRoles()
=> Illuminate\Database\Eloquent\Collection {#881
     all: [
       HttpOz\Roles\Models\Role {#893
         id: 1,
         name: "Admin",
         slug: "admin",
         ...
         pivot: Illuminate\Database\Eloquent\Relations\Pivot {#887
           user_id: 1,
           role_id: 1,
           ...
         },
       },
     ],
   }
>>> App\Models\User::find(2)->getRoles()
=> Illuminate\Database\Eloquent\Collection {#892
     all: [
       HttpOz\Roles\Models\Role {#826
         id: 1,
         name: "Admin",
         slug: "admin",
         ...
         pivot: Illuminate\Database\Eloquent\Relations\Pivot {#890
           user_id: 1,
           role_id: 1,
           ...
         },
       },
     ],
   }
>>> Cache::flush()
=> true
>>> App\Models\User::find(2)->getRoles()
=> Illuminate\Database\Eloquent\Collection {#896
     all: [
       HttpOz\Roles\Models\Role {#906
         id: 2,
         name: "Moderator",
         slug: "moderator",
         ...
         pivot: Illuminate\Database\Eloquent\Relations\Pivot {#900
           user_id: 2,
           role_id: 2,
           ...
         },
       },
     ],
   }
```

**Comment by cjmaxik** [comment]
So, https://github.com/httpoz/roles/pull/34 is my current implementation.

Btw, I have some weird problem with tests: at some random execution not all the roles would attaches. I am not sure, what cause this behavior - HasRole trait, Laravel's each() implementations or Laravel's factory result response. Here is my test seeder code:

```php
$userRole = Role::whereSlug('user')->first();
factory(App\Models\User::class, $users)->create()->each->attachRole($userRole);
```

**Comment by httpoz** [comment]
I have removed caching from master branch and if you could send a pull request on the develop branch I would appreciate it, just bothered that I may have inconvenienced a lot of you guys with the buggy release.

**Comment by cjmaxik** [comment]
@httpoz Done.
