### ISSUE TITLE
Suggestion for Groups

### ISSUE THREAD

**Issue by maig81** [httpoz/roles#28]
#Can I suggest a method for testing if the user is an a group (or something similar):
`
public function has_group($group){
    return ($this->getRoles()->where('group', 'LIKE', $group)->first() ? true : false);
}
`

I am using it in my User model, but i think it should be a part of Roles.

**Comment by httpoz** [comment]
I have added this in https://github.com/httpoz/roles/commit/ba8a0bef8ec210b5c3fa027c2c571dc562d81158 . So you would do:
```php
    $user->inGroup('system.managers');
```

I will however have it working in a v2.1 release as soon as possible.

**Comment by maig81** [comment]
Even better name :) Thanks!
