### ISSUE TITLE
Error after registering

### ISSUE THREAD

**Issue by JPortegijs** [httpoz/roles#30]
Hi,

I`m using the default Laravel Auth and trying to attach a default role to the registered user. This is what I have in my RegisterController:

`protected function create(array $data)
    {
        $userRole = Role::whereSlug('user')->first();

        $createUser = User::create([
            'name' => $data['name'],
            'email' => $data['email'],
            'password' => bcrypt($data['password']),
        ]);

        $createUser->attachRole($userRole);
    }`

It's working as intended, the user is created with a default role of an user. But I get the following error after registering: 

FatalThrowableError in SessionGuard.php line 407:
Type error: Argument 1 passed to Illuminate\Auth\SessionGuard::login() must implement interface Illuminate\Contracts\Auth\Authenticatable, null given, called in C:\xampp\htdocs\RAC\vendor\laravel\framework\src\Illuminate\Foundation\Auth\RegistersUsers.php on line 35

I tried looking it up, but couldn't find a solution. Do you have an idea?

Thanks in advance!

**Comment by httpoz** [comment]
sorry for the late response but as you can see here in the default method, you return the created user:
```php
/**
     * Create a new user instance after a valid registration.
     *
     * @param  array  $data
     * @return User
     */
    protected function create(array $data)
    {
        return User::create([
            'name' => $data['name'],
            'email' => $data['email'],
            'password' => bcrypt($data['password']),
        ]);
    }
```

You just need to add the following after you attach your role:
```php
return $createUser;
```

**Comment by JPortegijs** [comment]
Why can't I think of a simple solution like this... 

Thank you so much!

**Comment by httpoz** [comment]
It's the simple stuff. That's what gets ya!
