### ISSUE TITLE
Failing relationships

### ISSUE THREAD

**Issue by hrabbit** [httpoz/roles#32]
I'm trying to get this module working correctly, and after following the instructions to the letter, I seem to be having trouble populating the user with any roles.

I added the seed information with the following

```
<?php

use Illuminate\Database\Seeder;

class UserRolesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \HttpOz\Roles\Models\Role::create([
        	'name' => 'Admin',
        	'slug' => 'admin',
        	'description' => 'Custodians of the system.', // optional
   		]);

    	\HttpOz\Roles\Models\Role::create([
        	'name' => 'Staff',
        	'slug' => 'staff',
        	'description' => 'All staff members',
        	'group' => 'default' // optional, set as 'default' by default
    	]);

    	\HttpOz\Roles\Models\Role::create([
        	'name' => 'Technician',
        	'slug' => 'technician',
        	'description' => 'Customer visiting technicians',
    	]);
    }
}
```

Which populated the roles table perfectly

I've adapted the User.php model to include the trait as described
```
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

use HttpOz\Roles\Traits\HasRole;
use HttpOz\Roles\Contracts\HasRole as HasRoleContract;

class User extends Authenticatable implements HasRoleContract
{
    use Notifiable, HasRole;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

}
```

I've seeded my user table seeder with
```
<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	$adminRole = \HttpOz\Roles\Models\Role::whereSlug('admin')->first();
    	$staffRole = \HttpOz\Roles\Models\Role::whereSlug('staff')->first();
    	$technicianRole = \HttpOz\Roles\Models\Role::whereSlug('technician')->first();

    	$user = \App\User::create([
        	'name' => 'Foo Bar',
       		'email' => 'user@doman',
       		'password' => 'someencryptedpassword',
    	]);
    	$user->attachRole($staffRole);
    	$user->attachRole($adminRole);
    }
}
```

From looking at the database, I can see that this populated the role_user table with records to match, however, when I try and perform any checks for a role, it always returns false (outside of the pretend option)

example
```
    public function index()
    {
        $user = \Auth::user();
        dd($user);
        return view('home');
    }
```
result
```
User {#202 ▼
  #fillable: array:3 [▶]
  #hidden: array:2 [▶]
  #connection: null
  #table: null
  #primaryKey: "id"
  #keyType: "int"
  +incrementing: true
  #with: []
  #perPage: 15
  +exists: true
  +wasRecentlyCreated: false
  #attributes: array:8 [▼
    "id" => 1
    "name" => "Foo Bar",
    "email" => "user@doman",
    "password" => "someencryptedpassword",
    "status" => 1
    "remember_token" => null
    "created_at" => "2017-04-04 03:26:47"
    "updated_at" => "2017-04-04 03:26:47"
  ]
  #original: array:8 [▶]
  #casts: []
  #dates: []
  #dateFormat: null
  #appends: []
  #events: []
  #observables: []
  #relations: []
  #touches: []
  +timestamps: true
  #visible: []
  #guarded: array:1 [▶]
  #rememberTokenName: "remember_token"
  #roles: null
}
```

Strangely, performing
```
$admins = \HttpOz\Roles\Models\Role::find(1)->users;
dd($admins);
```

returns
```
User {#202 ▼
  #fillable: array:3 [▶]
  #hidden: array:2 [▶]
  #connection: null
  #table: null
  #primaryKey: "id"
  #keyType: "int"
  +incrementing: true
  #with: []
  #perPage: 15
  +exists: true
  +wasRecentlyCreated: false
  #attributes: array:8 [▼
    "id" => 1
    "name" => "Foo Bar",
    "email" => "user@doman",
    "password" => "someencryptedpassword",
    "status" => 1
    "remember_token" => null
    "created_at" => "2017-04-04 03:26:47"
    "updated_at" => "2017-04-04 03:26:47"
  ]
  #original: array:8 [▶]
  #casts: []
  #dates: []
  #dateFormat: null
  #appends: []
  #events: []
  #observables: []
  #relations: []
  #touches: []
  +timestamps: true
  #visible: []
  #guarded: array:1 [▶]
  #rememberTokenName: "remember_token"
  #roles: null
}
```
I'd love to hear that I'm doing something silly and walk away with my tail between my legs so be as critical as you like. :)

**Comment by httpoz** [comment]
Everything you have done is right.

``` Auth::user()->getRoles()``` should show you the roles for the user. So essentially the roles have been assigned. Is there something in particular (a behavior) you expected?

**Comment by hrabbit** [comment]
Hi Oscar,

Thanks for getting back to me, I'm not ever getting a valid response when testing for a role

eg.
```
        $user = \App\User::find(1);

        if ($user->isRole('admin')) { // you can pass an id or slug
            dd("is admin");
        // do something
        }
```
Or in a blade template
```
@role('admin')
 I'm an admin!!
@endrole
```
Never fires as true even though I have the following details in the database

```
MariaDB [sp1]> select * from users\G
*************************** 1. row ***************************
            id: 1
          name: Foo Bar,
        email: user@doman
        password: someencryptedpassword
        status: 1
remember_token: 234trfds45tfedqwtegefwsdw4twdef4re3w
    created_at: 2017-04-04 03:26:47
    updated_at: 2017-04-04 03:26:47
1 row in set (0.00 sec)

MariaDB [sp1]> select * from roles\G
*************************** 1. row ***************************
         id: 1
       name: Admin
       slug: admin
description: Custodians of the system.
      group: default
 created_at: 2017-04-04 03:26:47
 updated_at: 2017-04-04 03:26:47
*************************** 2. row ***************************
         id: 2
       name: Staff
       slug: staff
description: All staff members
      group: default
 created_at: 2017-04-04 03:26:47
 updated_at: 2017-04-04 03:26:47
*************************** 3. row ***************************
         id: 3
       name: Technician
       slug: technician
description: Customer visiting technicians
      group: default
 created_at: 2017-04-04 03:26:47
 updated_at: 2017-04-04 03:26:47
3 rows in set (0.00 sec)

MariaDB [sp1]> select * from role_user\G
*************************** 1. row ***************************
        id: 1
   role_id: 2
   user_id: 1
created_at: 2017-04-04 03:26:47
updated_at: 2017-04-04 03:26:47
*************************** 2. row ***************************
        id: 2
   role_id: 1
   user_id: 1
created_at: 2017-04-04 03:26:47
updated_at: 2017-04-04 03:26:47
2 rows in set (0.00 sec)
```

**Comment by hrabbit** [comment]
Missed a detail in here

```
dd(\Auth::user()->getRoles());
```

returns

```
Collection {#213 ▼
  #items: []
}
```

**Comment by httpoz** [comment]
Are you on v2.1.0 or v2.1.1?

**Comment by Krato** [comment]
Is giving me the same error.

Can be fixed with: `php artisan cache:clear`.

But, there's some way to remove cache? Or check for standard relation if cache returns null? 

Thanks!

**Comment by httpoz** [comment]
@Krato what version are you on, there was an issue with 2.1.0 that caused this and a hotfix 2.1.1 should have resolved this.

**Comment by Krato** [comment]
@httpoz Yes, I was on 2.1.0 version.

Maybe that was the problem. Thanks!

**Comment by hrabbit** [comment]
Sorry @httpoz, left the office for the day. I can check tomorrow and if I'm on the wrong one, I'll update. Thanks for your time. I'll let you know the outcome either way.

**Comment by hrabbit** [comment]
Okay, so interesting....

I was running "^2.1" which is the version that was installed when using

    composer require httpoz/roles

This is the defined method when reading https://httpoz.github.io/roles/installation/

Changing to 2.1.1 seems to have corrected the issue. 

Thanks heaps @httpoz, and @Krato for sharing the information that solved the issue for me. :smile: 

The next question is, is there a way to force the cache to flush when a change has occurred? I know there is a cache timer but that only expires things over a period of time rather than when a user has been assigned or revoked from a role itself. My concern is that if I revoke a role from a user, I'd want that to occur straight away.

I know I'm now thread hijacking so let me know if you would prefer a different issue request for this one.

**Comment by cjmaxik** [comment]
@hrabbit Basically, I have my own caching function in model for now (since my pull request has failed), and I just forget exact user role cache:
```php
Cache::forget('roles.user_' . $this->id);
```

**Comment by hrabbit** [comment]
@cjmaxik Thanks for that, makes sense, I'm actually tempted to disable the cache entirely as the user count is only about 20 - 40 people.

**Comment by httpoz** [comment]
I have removed caching from the active branch. please update to v2.1.2, I will take a more cautious approach now regarding testing. In the next implementation of caching, caching will be an option which would fit @hrabbit's use case. Thanks for all the help and I apologize for the inconvenience.

**Comment by hrabbit** [comment]
After upgrading to 2.1.2, caching issues(?) are gone.. Cheers @httpoz 

I appreciate that caching would be hugely powerful for heaps of users though.

Without trying to define how you envision the package, I can't help but think about having the ability to flush the cache on a single user whenever was required in order to ensure roles were updated to match straight away. Without digging through the code, I'm only speculating on the complexity of this however.

Again, thanks for the update, hugely appreciate your work! :D
