### ISSUE TITLE
migrate:refresh/reset/rollback throwable error

### ISSUE THREAD

**Issue by hotsaucejake** [httpoz/roles#38]
Using Laravel 5.4

Whenever I try a ````php artisan migrate:refresh```` or similar command I receive an error:

````
[Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Too few arguments to function CreateRoleUserTable::down(), 0 passed in
    /vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php on line 353 and 
    exactly 1 expected
````

I had to change my ````database/migrations/*_create_role_user_table.php```` file to:

````
/**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
      Schema::table('role_user', function (Blueprint $table) {
         $table->dropForeign('role_user_role_id_foreign');
         $table->dropForeign('role_user_user_id_foreign');
      });

      Schema::dropIfExists('role_user');
    }
````

Not sure if this is the best method or best way of going about it, but all refreshes/resets/rollbacks work for me now.

**Comment by httpoz** [comment]
Yes it is, I have added this into the development branch and will merge it into the main branch. Thanks.

**Comment by MeiRct** [comment]
There's also my PR for that https://github.com/httpoz/roles/pull/39

**Comment by httpoz** [comment]
Sorted, tagging.
