### ISSUE TITLE
Class 'Bican\Roles\Models\Role' not found

### ISSUE THREAD

**Issue by erdemozveren** [httpoz/roles#45]
Hi,im using laravel 5.4 and i have error when i try to use attachRole method
```
(1/1) FatalErrorException
Class 'Bican\Roles\Models\Role' not found
in HasRelationships.php (line 487)
``` 
Here is my user model;
```
class User extends Model implements HasRoleContract,Authenticatable
{
use \Illuminate\Auth\Authenticatable;
use NotifableTrait;
use HasRole;
and so...
```
In controller 
`$user->attachRole(4)`
I don't know where is the problem and how to solve it

**Comment by httpoz** [comment]
What version of the package are you using?

**Comment by erdemozveren** [comment]
Sorry for that, im using ^2.2

**Comment by httpoz** [comment]
Did you set the package up following the docs? Were you using Bican Roles
before?

**Comment by erdemozveren** [comment]
Yes,first i install Bican Roles then i realize that not working and uninstall Bican Roles.And install this following the docs

**Comment by httpoz** [comment]
Issue there appears you may still be referencing Bican Roles. I would
suggest looking at the docs on how to set up your user model to use the
package.

**Comment by erdemozveren** [comment]
Ok.I did some things before but its not worked.I review my files maybe there is something referencing Bican Roles as you said.I write when i solve

**Comment by erdemozveren** [comment]
Oh i finally found it! I don't know but "php artisan vendor:publish --provider="HttpOz\Roles\RolesServiceProvider" doesn't overwrite "app/roles.php" (btw i did not know this file exist)
So I delete the "app/roles.php" and do vendor publish command again and Its worked.Thank you for time.

**Comment by httpoz** [comment]
Shweet, glad you found a solution.
