### ISSUE TITLE
FatalErrorException in VerifyGroup.php line 42: Class 'HttpOz\Roles\Exceptions\GroupDeniedException' not found

### ISSUE THREAD

**Issue by ramizan** [httpoz/roles#5]
FatalErrorException in VerifyGroup.php line 42: Class 'HttpOz\Roles\Exceptions\GroupDeniedException' not found

???

**Comment by httpoz** [comment]
pushing a fix in the next 15 minutes. Apologies there @ramizan

**Comment by httpoz** [comment]
https://github.com/httpoz/roles/commit/3ed84d9d8be8700e6ea61b375a088170a53720d6
