### ISSUE TITLE
User object isn't immediately updated

### ISSUE THREAD

**Issue by chrsc** [httpoz/roles#50]
Doing behavioural driven development I came across a scenario where I needed to assign a role, and then assert that the user has the role, it kept failing because the user object did not get updated immediately. 

Doesn't work:

```
public function iAmAAdminUser()
{
        $user = Auth::user();
        // using factory to create role
        $role = $this->createRole('Admin User', 'admin.user');
        $user->attachRole($role->id);
        PHPUnit::assertTrue($user->hasRole('admin.user'));
}
```

works:
```
public function iAmAAdminUser()
{
        $user = Auth::user();
        // using factory to create role
        $role = $this->createRole('Admin User', 'admin.user');
        $user->attachRole($role->id);
        // reload the user object
        $user = User::find($user->id);
        PHPUnit::assertTrue($user->hasRole('admin.user'));
}
```

**Comment by mgsmus** [comment]
The ones not get updated are the relationships because of design (performance reasons maybe?). You can get User object with fresh relationships with _fresh_ : 

`PHPUnit::assertTrue($user->fresh('roles')->hasRole('admin.user'))`

**Comment by httpoz** [comment]
Apologies for the late response, I have not worked that much with testing, just recently got started so I cannot for certain expand further on @mgsmus observation.

**Comment by chrsc** [comment]
@mgsmus thanks! I'll try that and should simplify the BDD code too.
