### ISSUE TITLE
Laravel 5.5

### ISSUE THREAD

**Issue by danielantoniobs** [httpoz/roles#54]
Any support for 5.5 coming?

**Comment by httpoz** [comment]
in the next week. Just need to tag a release.

**Comment by galdazbiz** [comment]
next week?

**Comment by httpoz** [comment]
Just need to get code coverage up to 90%, currently at 67%. “Next week” is more accurate today than it was 2 months ago.

**Comment by httpoz** [comment]
master branch should work for Laravel 5.5, tagging version 3 over the weekend.
