### ISSUE TITLE
Migration from Bican\Roles to your Repo

### ISSUE THREAD

**Issue by jandayanan** [httpoz/roles#6]
Hi. 

Do I need to do anything special when I want to convert from Bican\Roles to your implementation? I want to migrate from that repo to your repo since I want to upgrade from Laravel 5.1.x to 5.3

Thanks in advance for your response

**Comment by httpoz** [comment]
It depends on 2 things largely. 
1. Are you currently using levels?
2. Are you currently using permissions?

Levels have been replaced with groups in this package and permissions were omitted entirely. Assuming you were not using either:
1. run a migration against your roles table to rename your `level` column to `group`. 
2. remove Bican\Roles package
3. remove this package
4. update all usage of the Bican\Roles to HttpOz\Roles
