### ISSUE TITLE
Update Roles

### ISSUE THREAD

**Issue by StanBarrows** [httpoz/roles#62]
Hey there,

A common problem is to update roles, because you need to take existing roles and add the new roles. Therefore It would be nice if there is a solution provided by the package.

Something like this:

```
$roles =$user->roles->pluck('id');
$roles->push((int) $request->role_id);
$user->syncRoles($roles->toArray());
```

At the end maybe something like this:

`$user->updateRoles($roles);`

Cheers,
Stan

**Comment by httpoz** [comment]
I believe the package should allow a simple API to update a given set of roles and not the logic to calculate what the suitable set of rules is. I will revisit my position on this if you insist.
