### ISSUE TITLE
syncRoles - could it be clearer?

### ISSUE THREAD

**Issue by willcrobinson** [httpoz/roles#8]
Just a suggestion - might it be a good idea to change the `syncRoles` method name to `setRoles` or similar? I found the concept quite confusing compared to the rest of the clearly named methods.

Figured it out by having a look at the code and using Artisan's tinker to see what was returned and the effect but probably would have gotten it straight away if it had been named something like the above.

If not, maybe an extra line in the README would do the trick.

**Comment by httpoz** [comment]
I agree with this, however I had opted to go with what others had gotten familiar with in other repos. Not sure the effect it would have on people using the package if we changed the method name. Another option is to have a method `setRoles` that "calls" the `syncRoles` method.

But I like this option better:

> If not, maybe an extra line in the README would do the trick.

Are you open to propose the **extra line**?
