### ISSUE TITLE
Cannot declare class CreateRoleUserTable, because the name is already in use

### ISSUE THREAD

**Issue by codebros-nl** [httpoz/roles#80]
Somehow I keep getting the error that the CreateRoleUserTable migration is already being used.

I've checked all available migrations (even in the ones that have run into the database) but none have the similar class name.
Anyone else have run into this issue before?

Package version: 8.0.2
Laravel version: 8.56.0

**Comment by nicklace** [comment]
I do. Same error.
No fix found :/

**Comment by kantsverma** [comment]
I am getting the same error in Laravel 8

**Comment by nicklace** [comment]
Any news on this, it blocks all my deployements :s

**Comment by codebros-nl** [comment]
Hi all,

I've added a pull request to fix this issue. If desired, you can find my fork over here: https://github.com/codebros-nl/roles
